[versions]
# Accompanist
accompanist = "0.36.0"

# Android Gradle Plugin
agp = "8.13.2"

# AndroidX
activityCompose = "1.12.2"
appcompat = "1.7.1"
androidxNavigation = "2.9.6"
composeBom = "2025.12.01"
composeMaterialIcons = "1.7.8"
coreKtx = "1.17.0"
espressoCore = "3.7.0"
junitVersion = "1.3.0"
lifecycleRuntimeKtx = "2.10.0"
material = "1.13.0"

# Coil3
coil3 = "3.3.0"

# Dagger Hilt
daggerHilt = "2.57.2"

# Google Devtools KSP
devtoolsKsp = "2.3.4"

# JavaX
javax = "1"

# Junit
junit = "4.13.2"
junitJupiter = "6.0.1"

# Kizzy
kizzyRPC = "1.0.71"

# Kotlin
kotlin = "2.3.0"
kotlinxSerializationJson = "1.9.0"

# Ktor
ktor3 = "3.3.3"
ktorClientAndroid = "3.3.3"
ktorClientCore = "3.3.3"
ktorClientLogging = "3.3.3"
ktorClientWebsockets = "3.3.3"
orgJetbrainsKotlinPluginSerializationGradlePlugin = "2.3.0"

# Pine
xposedPine = "0.2.0"


[libraries]
# Accompanist
accompanist-navigation-animation = { group = "com.google.accompanist", name = "accompanist-navigation-animation", version.ref = "accompanist"}

# AndroidX
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "composeMaterialIcons" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Coil3
coil3-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil3" }
coil3-network-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil3" }

# Dagger Hilt
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "daggerHilt" }

# JavaX
javax = { group = "javax.inject", name = "javax.inject", version.ref = "javax"}

# Junit
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }

# Kizzy
kizzyRPC = { group = "com.github.dead8309", name = "KizzyRPC", version.ref = "kizzyRPC" }

# Kotlin
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Ktor
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktorClientAndroid" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktorClientLogging" }
ktor-client-websockets = { group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktorClientWebsockets" }
ktor3-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor3" }
ktor3-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor3" }
org-jetbrains-kotlin-plugin-serialization-gradle-plugin = { group = "org.jetbrains.kotlin.plugin.serialization", name = "org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "orgJetbrainsKotlinPluginSerializationGradlePlugin" }

# Pine
pine-xposed = { group = "top.canyie.pine", name = "xposed", version.ref = "xposedPine" }


[plugins]
# Android Gradle Plugin
android-application = { id = "com.android.application", version.ref = "agp" }

# Dagger Hilt
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt"}

# Google Devtools KSP
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtoolsKsp"}

# Kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }